# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: CI

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "signatures/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20
      - run: pnpm i
      - run: pnpm build
      - uses: hoverkraft-tech/compose-action@v2.0.1
      - run: pnpm test
